<a href="https://colab.research.google.com/github/noachzefanya/Project-KKA-EDA-Team/blob/main/Project_KKA_Team_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Loading

In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('/content/dataset_nilai_akademik_siswa.csv')
df

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu
0,SIS0004,Joko Prasetyo,XI RPL 2,KKA,uas,06/08/2026,46,Ibu Wati
1,SIS0020,Eka Putri,XI RPL 1,PKK,uts,12 Agustus 2026,"73,0",Bpk. Santoso
2,SIS0015,Nanda Pratama,XI RPL 3,Pemrograman Web,UAS,2026-08-15,69,Bpk. Santoso
3,SIS0046,Fajar Nugroho,XI RPL 2,Matematika,UH,10/08/2026,73,Bpk. Arifin
4,SIS0011,Ayu Lestari,XI RPL 2,Pemrograman Web,UH,6 Agustus 2026,53,Ibu Wati
...,...,...,...,...,...,...,...,...
74,SIS0036,Indah Permata,XI RPL 3,KKA,UTS,8 Agustus 2026,65,Bpk. Rendi
75,SIS0049,Putri Amelia,XI RPL 3,Basis Data,uas,2026-08-13,61 poin,Ibu Wati
76,SIS0005,Lukman Hakim,XI RPL 1,Bahasa Inggris,uas,2026-08-05,71,Ibu Dewi
77,SIS0057,Nanda Pratama,XI RPL 3,PKK,uas,2026-08-08,"45,0",Ibu Wati
78,SIS0074,Indah Permata,XI RPL 3,PKK,uas,12 Agustus 2026,59,Ibu Dewi

In [9]:
df.head()

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu
0,SIS0004,Joko Prasetyo,XI RPL 2,KKA,uas,06/08/2026,46,Ibu Wati
1,SIS0020,Eka Putri,XI RPL 1,PKK,uts,12 Agustus 2026,"73,0",Bpk. Santoso
2,SIS0015,Nanda Pratama,XI RPL 3,Pemrograman Web,UAS,2026-08-15,69,Bpk. Santoso
3,SIS0046,Fajar Nugroho,XI RPL 2,Matematika,UH,10/08/2026,73,Bpk. Arifin
4,SIS0011,Ayu Lestari,XI RPL 2,Pemrograman Web,UH,6 Agustus 2026,53,Ibu Wati

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_siswa        79 non-null     object
 1   nama            79 non-null     object
 2   kelas           79 non-null     object
 3   mata_pelajaran  79 non-null     object
 4   jenis_ujian     79 non-null     object
 5   tanggal_ujian   79 non-null     object
 6   nilai           75 non-null     object
 7   guru_pengampu   75 non-null     object
dtypes: object(8)
memory usage: 5.1+ KB

In [10]:
df.describe()

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu
count,79,79,79,79,79,79,75,75
unique,75,20,3,6,6,38,52,5
top,SIS0046,Lukman Hakim,XI RPL 3,PKK,UH,2026-08-05,73,Bpk. Arifin
freq,2,7,34,16,21,8,4,18

In [11]:
df.shape

(79, 8)

In [15]:
df[df.duplicated(keep=False)]

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu
3,SIS0046,Fajar Nugroho,XI RPL 2,Matematika,UH,10/08/2026,73,Bpk. Arifin
13,SIS0032,Fajar Nugroho,XI RPL 3,Matematika,UH,2026-08-09,79,NaN
34,SIS0037,Hendra Wijaya,XI RPL 2,Matematika,uh,2026-08-13,100,Bpk. Arifin
35,SIS0037,Hendra Wijaya,XI RPL 2,Matematika,uh,2026-08-13,100,Bpk. Arifin
45,SIS0046,Fajar Nugroho,XI RPL 2,Matematika,UH,10/08/2026,73,Bpk. Arifin
51,SIS0017,Oki Firmansyah,XI RPL 1,Matematika,UTS,2026-08-04,76 poin,Bpk. Rendi
65,SIS0017,Oki Firmansyah,XI RPL 1,Matematika,UTS,2026-08-04,76 poin,Bpk. Rendi
68,SIS0032,Fajar Nugroho,XI RPL 3,Matematika,UH,2026-08-09,79,NaN

In [22]:
print(df.duplicated().sum())

4

In [21]:
df[df.isna().any(axis=1)]

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu
8,SIS0025,Putri Amelia,XI RPL 1,Pemrograman Web,UH,2026-08-20,98,NaN
12,SIS0018,Lukman Hakim,XI RPL 3,Matematika,uh,10 Agustus 2026,NaN,Bpk. Arifin
13,SIS0032,Fajar Nugroho,XI RPL 3,Matematika,UH,2026-08-09,79,NaN
16,SIS0012,Hendra Wijaya,XI RPL 2,Basis Data,UTS,2026-08-05,65,NaN
23,SIS0058,Lukman Hakim,XI RPL 1,Basis Data,uts,2026-08-04,NaN,Ibu Dewi
49,SIS0055,Ayu Lestari,XI RPL 2,Pemrograman Web,uas,2026-08-11,NaN,Bpk. Santoso
56,SIS0071,Eka Putri,XI RPL 1,Pemrograman Web,UTS,2026-08-15,NaN,Bpk. Rendi
68,SIS0032,Fajar Nugroho,XI RPL 3,Matematika,UH,2026-08-09,79,NaN

In [23]:
print(df.isna().sum())

id_siswa          0
nama              0
kelas             0
mata_pelajaran    0
jenis_ujian       0
tanggal_ujian     0
nilai             4
guru_pengampu     4
dtype: int64

# Data CLeaning

In [16]:
df_clean = df.drop_duplicates().copy()

In [20]:
df_clean[df.isna().any(axis=1)]

/tmp/ipykernel_827/2858610803.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_clean[df.isna().any(axis=1)]

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu
8,SIS0025,Putri Amelia,XI RPL 1,Pemrograman Web,UH,2026-08-20,98,NaN
12,SIS0018,Lukman Hakim,XI RPL 3,Matematika,uh,10 Agustus 2026,NaN,Bpk. Arifin
13,SIS0032,Fajar Nugroho,XI RPL 3,Matematika,UH,2026-08-09,79,NaN
16,SIS0012,Hendra Wijaya,XI RPL 2,Basis Data,UTS,2026-08-05,65,NaN
23,SIS0058,Lukman Hakim,XI RPL 1,Basis Data,uts,2026-08-04,NaN,Ibu Dewi
49,SIS0055,Ayu Lestari,XI RPL 2,Pemrograman Web,uas,2026-08-11,NaN,Bpk. Santoso
56,SIS0071,Eka Putri,XI RPL 1,Pemrograman Web,UTS,2026-08-15,NaN,Bpk. Rendi

In [24]:
def bersihkan_nilai(val):
    if pd.isna(val):
        return np.nan
    val_str = str(val).lower().replace('poin', '').strip().replace(',', '.')
    try:
        angka = float(val_str)
        # Nilai 999 adalah kesalahan input data (skala nilai 0-100)
        if angka > 100:
            return np.nan
        return angka
    except ValueError:
        return np.nan

In [25]:
df_clean['nilai'] = df_clean['nilai'].apply(bersihkan_nilai)

In [26]:
df_clean['nilai'] = df_clean.groupby('mata_pelajaran')['nilai'].transform(lambda x: x.fillna(x.median()))

In [30]:
df_clean['guru_pengampu'] = df_clean['guru_pengampu'].fillna('Belum Terdata')

In [33]:
df_clean['jenis_ujian'] = df_clean['jenis_ujian'].str.upper()

In [34]:
df_clean

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu
0,SIS0004,Joko Prasetyo,XI RPL 2,KKA,UAS,06/08/2026,46.0,Ibu Wati
1,SIS0020,Eka Putri,XI RPL 1,PKK,UTS,12 Agustus 2026,73.0,Bpk. Santoso
2,SIS0015,Nanda Pratama,XI RPL 3,Pemrograman Web,UAS,2026-08-15,69.0,Bpk. Santoso
3,SIS0046,Fajar Nugroho,XI RPL 2,Matematika,UH,10/08/2026,73.0,Bpk. Arifin
4,SIS0011,Ayu Lestari,XI RPL 2,Pemrograman Web,UH,6 Agustus 2026,53.0,Ibu Wati
...,...,...,...,...,...,...,...,...
74,SIS0036,Indah Permata,XI RPL 3,KKA,UTS,8 Agustus 2026,65.0,Bpk. Rendi
75,SIS0049,Putri Amelia,XI RPL 3,Basis Data,UAS,2026-08-13,61.0,Ibu Wati
76,SIS0005,Lukman Hakim,XI RPL 1,Bahasa Inggris,UAS,2026-08-05,71.0,Ibu Dewi
77,SIS0057,Nanda Pratama,XI RPL 3,PKK,UAS,2026-08-08,45.0,Ibu Wati
78,SIS0074,Indah Permata,XI RPL 3,PKK,UAS,12 Agustus 2026,59.0,Ibu Dewi

In [35]:
df_clean.isnull().sum()

id_siswa          0
nama              0
kelas             0
mata_pelajaran    0
jenis_ujian       0
tanggal_ujian     0
nilai             0
guru_pengampu     0
dtype: int64

In [36]:
df_clean.duplicated().sum()

np.int64(0)

In [37]:
# a. Kolom Turunan: Menentukan status kelulusan berdasarkan batas KKM (75)
KKM = 75
df_clean['status_kelulusan'] = np.where(df_clean['nilai'] >= KKM, 'Tuntas', 'Remedial')

In [42]:
df_clean.head()

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu,status_kelulusan
0,SIS0004,Joko Prasetyo,XI RPL 2,KKA,UAS,06/08/2026,46.0,Ibu Wati,Remedial
1,SIS0020,Eka Putri,XI RPL 1,PKK,UTS,12 Agustus 2026,73.0,Bpk. Santoso,Remedial
2,SIS0015,Nanda Pratama,XI RPL 3,Pemrograman Web,UAS,2026-08-15,69.0,Bpk. Santoso,Remedial
3,SIS0046,Fajar Nugroho,XI RPL 2,Matematika,UH,10/08/2026,73.0,Bpk. Arifin,Remedial
4,SIS0011,Ayu Lestari,XI RPL 2,Pemrograman Web,UH,6 Agustus 2026,53.0,Ibu Wati,Remedial

# Data Manipulation

In [40]:
# b. Sorting: Mengurutkan dataset berdasarkan nilai tertinggi ke terendah
df_sorted = df_clean.sort_values(by='nilai', ascending=False)
print(df_sorted[['nama', 'kelas', 'mata_pelajaran', 'nilai', 'status_kelulusan']].head())

             nama     kelas   mata_pelajaran  nilai status_kelulusan
34  Hendra Wijaya  XI RPL 2       Matematika  100.0           Tuntas
8    Putri Amelia  XI RPL 1  Pemrograman Web   98.0           Tuntas
61      Eka Putri  XI RPL 2              KKA   96.0           Tuntas
40    Ayu Lestari  XI RPL 3              PKK   92.0           Tuntas
22   Lukman Hakim  XI RPL 1  Pemrograman Web   91.0           Tuntas

In [49]:
df_sorted

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu,status_kelulusan
34,SIS0037,Hendra Wijaya,XI RPL 2,Matematika,UH,2026-08-13,100.0,Bpk. Arifin,Tuntas
8,SIS0025,Putri Amelia,XI RPL 1,Pemrograman Web,UH,2026-08-20,98.0,Belum Terdata,Tuntas
61,SIS0038,Eka Putri,XI RPL 2,KKA,UTS,2026-08-11,96.0,Ibu Wati,Tuntas
40,SIS0029,Ayu Lestari,XI RPL 3,PKK,UH,8 Agustus 2026,92.0,Bpk. Rendi,Tuntas
22,SIS0022,Lukman Hakim,XI RPL 1,Pemrograman Web,UH,2026-08-15,91.0,Ibu Dewi,Tuntas
...,...,...,...,...,...,...,...,...,...
54,SIS0069,Dedi Saputra,XI RPL 1,PKK,UH,13/08/2026,44.0,Bpk. Santoso,Remedial
44,SIS0016,Maya Anggraini,XI RPL 2,Basis Data,UTS,6 Agustus 2026,43.0,Ibu Wati,Remedial
27,SIS0070,Citra Ningrum,XI RPL 2,Basis Data,UTS,04/08/2026,43.0,Bpk. Arifin,Remedial
5,SIS0056,Maya Anggraini,XI RPL 2,PKK,UTS,08/08/2026,42.0,Bpk. Santoso,Remedial
38,SIS0052,Oki Firmansyah,XI RPL 1,Pemrograman Web,UTS,15/08/2026,42.0,Bpk. Arifin,Remedial

In [44]:
# c. Filtering: Menyaring data siswa yang harus mengikuti remedial
remedial_list = df_clean[df_clean['status_kelulusan'] == 'Remedial']
print(f"\nJumlah ujian yang berstatus remedial: {len(remedial_list)} siswa.")

Jumlah ujian yang berstatus remedial: 61 siswa.

In [43]:
total_data = len(df_clean)
jumlah_remedial = len(remedial_list)
jumlah_tuntas = total_data - jumlah_remedial

persen_tuntas = (jumlah_tuntas / total_data) * 100
persen_remedial = (jumlah_remedial / total_data) * 100

print(f"Persentase Tuntas   : {persen_tuntas:.2f}% ({jumlah_tuntas} siswa)")
print(f"Persentase Remedial : {persen_remedial:.2f}% ({jumlah_remedial} siswa)")

Persentase Tuntas   : 18.67% (14 siswa)
Persentase Remedial : 81.33% (61 siswa)

In [50]:
ringkasan_mapel = df_clean.groupby('mata_pelajaran')['nilai'].agg(['count', 'mean', 'min', 'max']).reset_index()
print(ringkasan_mapel)

    mata_pelajaran  count       mean   min    max
0   Bahasa Inggris      7  67.500000  45.0   90.0
1       Basis Data     13  59.692308  43.0   74.0
2              KKA     12  64.250000  44.0   96.0
3       Matematika     12  66.083333  44.0  100.0
4              PKK     16  63.312500  42.0   92.0
5  Pemrograman Web     15  67.266667  42.0   98.0

In [53]:
ringkasan_kelas = df_clean.groupby('kelas')['nilai'].agg(['count','mean', 'min', 'max']).reset_index()
print(ringkasan_kelas)

      kelas  count       mean   min    max
0  XI RPL 1     20  67.075000  42.0   98.0
1  XI RPL 2     22  67.090909  42.0  100.0
2  XI RPL 3     33  61.121212  44.0   92.0